image: alpine

prepare:
    stage: prepare
    script:
        - apk add --no-cache libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev cmake g++ make

build:
    stage: build
    # instead of calling g++ directly you can also use some build toolkit like make
    # install the necessary build tools when needed
    # before_script:
    #   - apt update && apt -y install make autoconf
    script:
        - cmake build
        - cd build
        - make
